runtime: nodejs
env: flex
#service: prueba
resources:
  cpu: 0.5
  memory_gb: 1
  disk_size_gb: 10
manual_scaling:
  instances: 1
skip_files:
  - ^node_modules/(.*/)?
  - ^.nuxt/(.*/)?
  - Dockerfile_
